import logging
from typing import Optional

logger = logging.getLogger(__name__)

CATEGORY_ID_GROCERIES: int = 1
CATEGORY_ID_DINING: int = 2
CATEGORY_ID_TRANSPORT: int = 3
CATEGORY_ID_HEALTH: int = 4
CATEGORY_ID_FASHION: int = 5
CATEGORY_ID_DAILY: int = 6
CATEGORY_ID_LEISURE: int = 7
CATEGORY_ID_OTHER: int = 8

CONFIDENCE_HIGH: str = "high"
CONFIDENCE_MEDIUM: str = "medium"
CONFIDENCE_LOW: str = "low"


class RuleClassifier:
    STORE_KEYWORDS: dict[str, int] = {
        "イオン": CATEGORY_ID_GROCERIES,
        "ヨークマート": CATEGORY_ID_GROCERIES,
        "ライフ": CATEGORY_ID_GROCERIES,
        "マルエツ": CATEGORY_ID_GROCERIES,
        "西友": CATEGORY_ID_GROCERIES,
        "ダイエー": CATEGORY_ID_GROCERIES,
        "イトーヨーカドー": CATEGORY_ID_GROCERIES,
        "コープ": CATEGORY_ID_GROCERIES,
        "生協": CATEGORY_ID_GROCERIES,
        "業務スーパー": CATEGORY_ID_GROCERIES,
        "コストコ": CATEGORY_ID_GROCERIES,
        "ドン・キホーテ": CATEGORY_ID_GROCERIES,
        "セブンイレブン": CATEGORY_ID_GROCERIES,
        "ローソン": CATEGORY_ID_GROCERIES,
        "ファミリーマート": CATEGORY_ID_GROCERIES,
        "ミニストップ": CATEGORY_ID_GROCERIES,
        "デイリーヤマザキ": CATEGORY_ID_GROCERIES,
        "ポプラ": CATEGORY_ID_GROCERIES,
        "スリーエフ": CATEGORY_ID_GROCERIES,
        "マクドナルド": CATEGORY_ID_DINING,
        "モスバーガー": CATEGORY_ID_DINING,
        "ケンタッキー": CATEGORY_ID_DINING,
        "吉野家": CATEGORY_ID_DINING,
        "すき家": CATEGORY_ID_DINING,
        "松屋": CATEGORY_ID_DINING,
        "なか卯": CATEGORY_ID_DINING,
        "てんや": CATEGORY_ID_DINING,
        "リンガーハット": CATEGORY_ID_DINING,
        "餃子の王将": CATEGORY_ID_DINING,
        "大阪王将": CATEGORY_ID_DINING,
        "CoCo壱番屋": CATEGORY_ID_DINING,
        "ガスト": CATEGORY_ID_DINING,
        "サイゼリヤ": CATEGORY_ID_DINING,
        "デニーズ": CATEGORY_ID_DINING,
        "ジョナサン": CATEGORY_ID_DINING,
        "バーミヤン": CATEGORY_ID_DINING,
        "夢庵": CATEGORY_ID_DINING,
        "スターバックス": CATEGORY_ID_DINING,
        "タリーズ": CATEGORY_ID_DINING,
        "ドトール": CATEGORY_ID_DINING,
        "コメダ珈琲": CATEGORY_ID_DINING,
        "エクセルシオール": CATEGORY_ID_DINING,
        "ベローチェ": CATEGORY_ID_DINING,
        "ミスタードーナツ": CATEGORY_ID_DINING,
        "サブウェイ": CATEGORY_ID_DINING,
        "丸亀製麺": CATEGORY_ID_DINING,
        "はなまるうどん": CATEGORY_ID_DINING,
        "くら寿司": CATEGORY_ID_DINING,
        "スシロー": CATEGORY_ID_DINING,
        "かっぱ寿司": CATEGORY_ID_DINING,
        "はま寿司": CATEGORY_ID_DINING,
        "焼肉きんぐ": CATEGORY_ID_DINING,
        "しゃぶ葉": CATEGORY_ID_DINING,
        "JR": CATEGORY_ID_TRANSPORT,
        "東京メトロ": CATEGORY_ID_TRANSPORT,
        "大阪メトロ": CATEGORY_ID_TRANSPORT,
        "阪急": CATEGORY_ID_TRANSPORT,
        "阪神": CATEGORY_ID_TRANSPORT,
        "近鉄": CATEGORY_ID_TRANSPORT,
        "名鉄": CATEGORY_ID_TRANSPORT,
        "西鉄": CATEGORY_ID_TRANSPORT,
        "京急": CATEGORY_ID_TRANSPORT,
        "東急": CATEGORY_ID_TRANSPORT,
        "相鉄": CATEGORY_ID_TRANSPORT,
        "西武": CATEGORY_ID_TRANSPORT,
        "東武": CATEGORY_ID_TRANSPORT,
        "小田急": CATEGORY_ID_TRANSPORT,
        "京王": CATEGORY_ID_TRANSPORT,
        "Suica": CATEGORY_ID_TRANSPORT,
        "PASMO": CATEGORY_ID_TRANSPORT,
        "ICOCA": CATEGORY_ID_TRANSPORT,
        "manaca": CATEGORY_ID_TRANSPORT,
        "nimoca": CATEGORY_ID_TRANSPORT,
        "タクシー": CATEGORY_ID_TRANSPORT,
        "バス": CATEGORY_ID_TRANSPORT,
        "高速道路": CATEGORY_ID_TRANSPORT,
        "駐車場": CATEGORY_ID_TRANSPORT,
        "マツモトキヨシ": CATEGORY_ID_HEALTH,
        "ウエルシア": CATEGORY_ID_HEALTH,
        "ツルハ": CATEGORY_ID_HEALTH,
        "サンドラッグ": CATEGORY_ID_HEALTH,
        "クリエイト": CATEGORY_ID_HEALTH,
        "スギ薬局": CATEGORY_ID_HEALTH,
        "カワチ": CATEGORY_ID_HEALTH,
        "ダルマ薬局": CATEGORY_ID_HEALTH,
        "薬局": CATEGORY_ID_HEALTH,
        "クリニック": CATEGORY_ID_HEALTH,
        "病院": CATEGORY_ID_HEALTH,
        "診療所": CATEGORY_ID_HEALTH,
        "医院": CATEGORY_ID_HEALTH,
        "ユニクロ": CATEGORY_ID_FASHION,
        "GU": CATEGORY_ID_FASHION,
        "しまむら": CATEGORY_ID_FASHION,
        "ZARA": CATEGORY_ID_FASHION,
        "ザラ": CATEGORY_ID_FASHION,
        "H&M": CATEGORY_ID_FASHION,
        "GAP": CATEGORY_ID_FASHION,
        "無印良品": CATEGORY_ID_FASHION,
        "ABC-MART": CATEGORY_ID_FASHION,
        "ルミネ": CATEGORY_ID_FASHION,
        "アトレ": CATEGORY_ID_FASHION,
        "美容室": CATEGORY_ID_FASHION,
        "ヘアサロン": CATEGORY_ID_FASHION,
        "理髪店": CATEGORY_ID_FASHION,
        "ニトリ": CATEGORY_ID_DAILY,
        "ダイソー": CATEGORY_ID_DAILY,
        "セリア": CATEGORY_ID_DAILY,
        "キャンドゥ": CATEGORY_ID_DAILY,
        "カインズ": CATEGORY_ID_DAILY,
        "コーナン": CATEGORY_ID_DAILY,
        "ジョイフル本田": CATEGORY_ID_DAILY,
        "コジマ": CATEGORY_ID_DAILY,
        "ヤマダ電機": CATEGORY_ID_DAILY,
        "エディオン": CATEGORY_ID_DAILY,
        "ビックカメラ": CATEGORY_ID_DAILY,
        "ヨドバシ": CATEGORY_ID_DAILY,
        "TOHOシネマズ": CATEGORY_ID_LEISURE,
        "イオンシネマ": CATEGORY_ID_LEISURE,
        "ユナイテッドシネマ": CATEGORY_ID_LEISURE,
        "ムービーオン": CATEGORY_ID_LEISURE,
        "ゲオ": CATEGORY_ID_LEISURE,
        "TSUTAYA": CATEGORY_ID_LEISURE,
        "ゲームセンター": CATEGORY_ID_LEISURE,
        "カラオケ": CATEGORY_ID_LEISURE,
        "まんが喫茶": CATEGORY_ID_LEISURE,
        "ネットカフェ": CATEGORY_ID_LEISURE,
        "ボウリング": CATEGORY_ID_LEISURE,
        "スポーツジム": CATEGORY_ID_LEISURE,
        "ゴルフ": CATEGORY_ID_LEISURE,
        "書店": CATEGORY_ID_LEISURE,
        "図書館": CATEGORY_ID_LEISURE,
    }

    PRODUCT_KEYWORDS: dict[str, int] = {
        "牛乳": CATEGORY_ID_GROCERIES,
        "豆乳": CATEGORY_ID_GROCERIES,
        "ヨーグルト": CATEGORY_ID_GROCERIES,
        "チーズ": CATEGORY_ID_GROCERIES,
        "バター": CATEGORY_ID_GROCERIES,
        "卵": CATEGORY_ID_GROCERIES,
        "たまご": CATEGORY_ID_GROCERIES,
        "パン": CATEGORY_ID_GROCERIES,
        "食パン": CATEGORY_ID_GROCERIES,
        "米": CATEGORY_ID_GROCERIES,
        "お米": CATEGORY_ID_GROCERIES,
        "野菜": CATEGORY_ID_GROCERIES,
        "果物": CATEGORY_ID_GROCERIES,
        "果実": CATEGORY_ID_GROCERIES,
        "肉": CATEGORY_ID_GROCERIES,
        "鶏肉": CATEGORY_ID_GROCERIES,
        "豚肉": CATEGORY_ID_GROCERIES,
        "牛肉": CATEGORY_ID_GROCERIES,
        "魚": CATEGORY_ID_GROCERIES,
        "刺身": CATEGORY_ID_GROCERIES,
        "豆腐": CATEGORY_ID_GROCERIES,
        "納豆": CATEGORY_ID_GROCERIES,
        "味噌": CATEGORY_ID_GROCERIES,
        "醤油": CATEGORY_ID_GROCERIES,
        "塩": CATEGORY_ID_GROCERIES,
        "砂糖": CATEGORY_ID_GROCERIES,
        "油": CATEGORY_ID_GROCERIES,
        "サラダ油": CATEGORY_ID_GROCERIES,
        "マヨネーズ": CATEGORY_ID_GROCERIES,
        "ケチャップ": CATEGORY_ID_GROCERIES,
        "ソース": CATEGORY_ID_GROCERIES,
        "だし": CATEGORY_ID_GROCERIES,
        "麺類": CATEGORY_ID_GROCERIES,
        "パスタ": CATEGORY_ID_GROCERIES,
        "うどん": CATEGORY_ID_GROCERIES,
        "そば": CATEGORY_ID_GROCERIES,
        "ラーメン": CATEGORY_ID_GROCERIES,
        "カップ麺": CATEGORY_ID_GROCERIES,
        "カレー": CATEGORY_ID_GROCERIES,
        "レトルト": CATEGORY_ID_GROCERIES,
        "缶詰": CATEGORY_ID_GROCERIES,
        "冷凍食品": CATEGORY_ID_GROCERIES,
        "冷凍": CATEGORY_ID_GROCERIES,
        "アイス": CATEGORY_ID_GROCERIES,
        "ジュース": CATEGORY_ID_GROCERIES,
        "炭酸": CATEGORY_ID_GROCERIES,
        "水": CATEGORY_ID_GROCERIES,
        "お茶": CATEGORY_ID_GROCERIES,
        "コーヒー": CATEGORY_ID_GROCERIES,
        "紅茶": CATEGORY_ID_GROCERIES,
        "スナック": CATEGORY_ID_GROCERIES,
        "お菓子": CATEGORY_ID_GROCERIES,
        "チョコ": CATEGORY_ID_GROCERIES,
        "チョコレート": CATEGORY_ID_GROCERIES,
        "ビスケット": CATEGORY_ID_GROCERIES,
        "クッキー": CATEGORY_ID_GROCERIES,
        "飴": CATEGORY_ID_GROCERIES,
        "ガム": CATEGORY_ID_GROCERIES,
        "定食": CATEGORY_ID_DINING,
        "弁当": CATEGORY_ID_DINING,
        "お弁当": CATEGORY_ID_DINING,
        "ランチ": CATEGORY_ID_DINING,
        "セット": CATEGORY_ID_DINING,
        "バーガー": CATEGORY_ID_DINING,
        "ハンバーガー": CATEGORY_ID_DINING,
        "ピザ": CATEGORY_ID_DINING,
        "パスタセット": CATEGORY_ID_DINING,
        "ラーメン一杯": CATEGORY_ID_DINING,
        "寿司": CATEGORY_ID_DINING,
        "うどんセット": CATEGORY_ID_DINING,
        "日替わり": CATEGORY_ID_DINING,
        "特定食": CATEGORY_ID_DINING,
        "電車": CATEGORY_ID_TRANSPORT,
        "バス代": CATEGORY_ID_TRANSPORT,
        "運賃": CATEGORY_ID_TRANSPORT,
        "乗車": CATEGORY_ID_TRANSPORT,
        "交通費": CATEGORY_ID_TRANSPORT,
        "切符": CATEGORY_ID_TRANSPORT,
        "定期": CATEGORY_ID_TRANSPORT,
        "ガソリン": CATEGORY_ID_TRANSPORT,
        "駐車": CATEGORY_ID_TRANSPORT,
        "高速": CATEGORY_ID_TRANSPORT,
        "ETC": CATEGORY_ID_TRANSPORT,
        "薬": CATEGORY_ID_HEALTH,
        "医薬品": CATEGORY_ID_HEALTH,
        "サプリ": CATEGORY_ID_HEALTH,
        "サプリメント": CATEGORY_ID_HEALTH,
        "ビタミン": CATEGORY_ID_HEALTH,
        "マスク": CATEGORY_ID_HEALTH,
        "包帯": CATEGORY_ID_HEALTH,
        "絆創膏": CATEGORY_ID_HEALTH,
        "点眼": CATEGORY_ID_HEALTH,
        "目薬": CATEGORY_ID_HEALTH,
        "風邪薬": CATEGORY_ID_HEALTH,
        "解熱剤": CATEGORY_ID_HEALTH,
        "胃薬": CATEGORY_ID_HEALTH,
        "整腸剤": CATEGORY_ID_HEALTH,
        "診察": CATEGORY_ID_HEALTH,
        "処方": CATEGORY_ID_HEALTH,
        "検査": CATEGORY_ID_HEALTH,
        "服": CATEGORY_ID_FASHION,
        "シャツ": CATEGORY_ID_FASHION,
        "パンツ": CATEGORY_ID_FASHION,
        "スカート": CATEGORY_ID_FASHION,
        "コート": CATEGORY_ID_FASHION,
        "ジャケット": CATEGORY_ID_FASHION,
        "下着": CATEGORY_ID_FASHION,
        "靴下": CATEGORY_ID_FASHION,
        "靴": CATEGORY_ID_FASHION,
        "スニーカー": CATEGORY_ID_FASHION,
        "サンダル": CATEGORY_ID_FASHION,
        "バッグ": CATEGORY_ID_FASHION,
        "カバン": CATEGORY_ID_FASHION,
        "化粧品": CATEGORY_ID_FASHION,
        "コスメ": CATEGORY_ID_FASHION,
        "口紅": CATEGORY_ID_FASHION,
        "ファンデ": CATEGORY_ID_FASHION,
        "シャンプー": CATEGORY_ID_FASHION,
        "コンディショナー": CATEGORY_ID_FASHION,
        "洗剤": CATEGORY_ID_DAILY,
        "柔軟剤": CATEGORY_ID_DAILY,
        "漂白剤": CATEGORY_ID_DAILY,
        "トイレットペーパー": CATEGORY_ID_DAILY,
        "ティッシュ": CATEGORY_ID_DAILY,
        "ゴミ袋": CATEGORY_ID_DAILY,
        "食器用洗剤": CATEGORY_ID_DAILY,
        "スポンジ": CATEGORY_ID_DAILY,
        "歯ブラシ": CATEGORY_ID_DAILY,
        "歯磨き粉": CATEGORY_ID_DAILY,
        "石鹸": CATEGORY_ID_DAILY,
        "ボディソープ": CATEGORY_ID_DAILY,
        "電池": CATEGORY_ID_DAILY,
        "電球": CATEGORY_ID_DAILY,
        "ライター": CATEGORY_ID_DAILY,
        "映画": CATEGORY_ID_LEISURE,
        "観覧": CATEGORY_ID_LEISURE,
        "チケット": CATEGORY_ID_LEISURE,
        "入場": CATEGORY_ID_LEISURE,
        "ゲーム": CATEGORY_ID_LEISURE,
        "本": CATEGORY_ID_LEISURE,
        "雑誌": CATEGORY_ID_LEISURE,
        "漫画": CATEGORY_ID_LEISURE,
        "CD": CATEGORY_ID_LEISURE,
        "DVD": CATEGORY_ID_LEISURE,
        "Blu-ray": CATEGORY_ID_LEISURE,
        "フィットネス": CATEGORY_ID_LEISURE,
        "水泳": CATEGORY_ID_LEISURE,
        "テニス": CATEGORY_ID_LEISURE,
        "ゴルフ場": CATEGORY_ID_LEISURE,
    }

    # (min_amount_inclusive, max_amount_exclusive, category_id)
    AMOUNT_RULES: list[tuple[int, int, int]] = [
        (0, 500, CATEGORY_ID_GROCERIES),
        (500, 5000, CATEGORY_ID_OTHER),
        (5000, 999999, CATEGORY_ID_OTHER),
    ]

    def classify(
        self,
        store_name: Optional[str],
        items: list[dict],
        amount: Optional[int],
    ) -> dict:
        if store_name:
            for keyword, category_id in self.STORE_KEYWORDS.items():
                if keyword in store_name:
                    logger.debug(
                        "DEBUG: Classified by store keyword '%s' -> category_id=%d",
                        keyword,
                        category_id,
                    )
                    return {
                        "category_id": category_id,
                        "confidence": CONFIDENCE_HIGH,
                    }

        item_names = " ".join(item.get("name", "") for item in items)
        combined_text = f"{store_name or ''} {item_names}"
        for keyword, category_id in self.PRODUCT_KEYWORDS.items():
            if keyword in combined_text:
                logger.debug(
                    "DEBUG: Classified by product keyword '%s' -> category_id=%d",
                    keyword,
                    category_id,
                )
                return {
                    "category_id": category_id,
                    "confidence": CONFIDENCE_MEDIUM,
                }

        if amount is not None:
            for min_amt, max_amt, category_id in self.AMOUNT_RULES:
                if min_amt <= amount < max_amt:
                    logger.debug(
                        "DEBUG: Classified by amount range [%d, %d) -> category_id=%d",
                        min_amt,
                        max_amt,
                        category_id,
                    )
                    return {
                        "category_id": category_id,
                        "confidence": CONFIDENCE_LOW,
                    }

        logger.debug("DEBUG: Classification fallback to 'その他' (category_id=%d)", CATEGORY_ID_OTHER)
        return {
            "category_id": CATEGORY_ID_OTHER,
            "confidence": None,
        }
